# Generated by Django 3.2.16 on 2025-01-14 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'ингредиенты в рецепт', 'verbose_name_plural': 'Ингредиенты в рецепты'},
        ),
    ]
