# Generated by Django 3.2.16 on 2025-01-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Добавьте изображение рецепта', upload_to='recipes/images/', verbose_name='Фото'),
        ),
    ]
